#mysql数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zxfdmysql
    driver-class-name: com.mysql.cj.jdbc.Driver
